package med.voll.api.domain.medic;

public enum Speciality {
    ORTHOPEDIST,
    CARDIOLOGIST,
    GYNECOLOGIST,
    PEDIATRICIAN,
    DERMATOLOGIST,
    NEUROLOGIST,
    PSYCHIATRIST,
    UROLOGIST,
    ENDOCRINOLOGIST,
    ONCOLOGIST,
    RADIOLOGIST,
    GASTROENTEROLOGIST,
    HEMATOLOGIST,
    IMMUNOLOGIST,
    NEPHROLOGIST,
    OPHTHALMOLOGIST,
    PULMONOLOGIST,
    RHEUMATOLOGIST
}
